version: "3.8"

services:
  mongo_db:
    image: mongo:8.0-noble
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: RealEstateDB
    ports:
      - "27017:27017"
    volumes:
      - mongo_db_data:/data/db

  mongo_express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo_db
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_BASICAUTH_ENABLED: false
    depends_on:
      - mongo_db

volumes:
  mongo_db_data:
