version: "3.8"

services:
  mongo_db:
    image: mongo:8.0-noble
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: RealEstateDB
    ports:
      - "27017:27017"
    volumes:
      - mongo_db_data:/data/db

  mongo_express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo_db
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_BASICAUTH_ENABLED: false
    depends_on:
      - mongo_db

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: supersecret
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  mongo_db_data:
  minio_data:
